name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'release/**'
  workflow_dispatch:  # 手動実行を有効化
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v1.0.0'
jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: |
          dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./publish/win-x64

      - name: List files (debugging)
        run: |
          Get-ChildItem -Path "./publish/win-x64/" -Recurse
        shell: pwsh

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path "./publish/win-x64/FaraDeviceChecker.exe", "README.md" -DestinationPath "./FaraDeviceChecker-${{ github.ref_name }}-win-x64.zip"
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./publish/win-x64/FaraDeviceChecker.exe
            ./FaraDeviceChecker-${{ github.ref_name }}-win-x64.zip
          body: |
            ## FaraDeviceChecker ${{ github.ref_name }}
            
            Windows用オーディオデバイス診断ツール
            
            ### ダウンロード
            - **FaraDeviceChecker-${{ github.ref_name }}-win-x64.zip**: Windows 64bit版
            
            ### 使用方法
            1. ZIPファイルをダウンロード・解凍
            2. `FaraDeviceChecker.exe` をダブルクリックで実行
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}